                                              NUMPY:
                                          ALLOW SEVERAL MATHEMATICAL OPERATIONS
                                          FAST OPERATIONS

In [1]:
import numpy as np

###              LIST VS NUMPY TIME TAKEN

In [2]:
from time import process_time

In [4]:
python_list=[i for i  in range(10000)]
start_time=process_time()
python_list=[i+5 for  i in python_list]
end_time=process_time()
print(end_time-start_time)


0.0016530299999999443


In [6]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)


0.0014167419999999709


#                                  NUMPY ARRAYS

In [7]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [10]:
a=np.array([(1,2),(3,4),(5,8)])
print(a)


[[1 2]
 [3 4]
 [5 8]]


In [13]:
a.shape

(3, 2)

In [15]:
c=np.array([(1,2,3,4)],dtype=float)
print(c)

[[1. 2. 3. 4.]]


#                                                  INITIAL PLACEHOLDERS

In [17]:
# initiallizing zero to the matrix 
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
# filling the matrix with a particular number 
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:

# random value matrix
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
# create a numpy array with random values
b=np.random.random((3,5))

In [23]:
c=np.random.randint(10,100,(3,5))
print(c)

[[17 91 94 96 92]
 [89 67 28 47 72]
 [97 40 97 52 24]]


In [25]:
s=np.linspace(10,30,5)
print(s)

[10. 15. 20. 25. 30.]


In [26]:
e=np.arange(10,30,5)
print(e)


[10 15 20 25]


In [27]:
# number of dimensions
print(c.shape)

(3, 5)


In [28]:
print(c.ndim)

2


In [29]:
print(c.size)

15


In [30]:
print(c.dtype)

int64


                                                    FUNCTIONS IN NUMPY PYTHON 

In [31]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [32]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)


[[5 0 2]
 [2 2 6]
 [9 2 3]]
[[10 14 14]
 [17 10 16]
 [15 17 12]]


In [33]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[15 14 16]
 [19 12 22]
 [24 19 15]]
[[ -5 -14 -12]
 [-15  -8 -10]
 [ -6 -15  -9]]
[[ 50   0  28]
 [ 34  20  96]
 [135  34  36]]
[[0.5        0.         0.14285714]
 [0.11764706 0.2        0.375     ]
 [0.6        0.11764706 0.25      ]]


#              FUNCTIONS ON AN ARRAY 

In [35]:
trans2=a.T
print(trans2)
print(trans2.shape)


[[5 2 9]
 [0 2 2]
 [2 6 3]]
(3, 3)


In [37]:
b=a.reshape(3,3)
print(b)
print(b.shape)

[[5 0 2]
 [2 2 6]
 [9 2 3]]
(3, 3)
